Repository studiobakers/react-ui-toolkit, pull requests merged in 2021-04, with the labels that each got.

#60 feat(dropdown): Allow disabled options
  package.json
  src/dropdown/Dropdown.tsx
  src/dropdown/list/item/DropdownListItem.tsx
  src/dropdown/list/item/_dropdown-list-item.scss
  stories/1-Dropdown.stories.tsx
Labels: ready for review

#63 fix(input): Add type prop for color picker
  src/form/input/Input.tsx
  stories/0-Form.stories.tsx
Labels: Ready for new release

#55 feat(components) : Add Avatar component
  src/avatar/Avatar.tsx
  src/avatar/_avatar.scss
  src/index.ts
  stories/7-Avatar.stories.tsx
Labels: Ready for new release, ready for review

#59 feat(typeahead/select): Remove tags with Backspace key
  src/select/typeahead/TypeaheadSelect.tsx
Labels: Ready for new release, ready for review

#64 feat(textarea): Add Textarea component
  package-lock.json
  package.json
  rollup.config.js
  src/form/textarea/Textarea.tsx
  src/form/textarea/_textarea.scss
  src/index.ts
  stories/0-Form.stories.tsx
Labels: Ready for new release

#65 feat(dropdown): Add samples with icon/subtitle/context/menu
  src/dropdown/list/item/DropdownListItem.tsx
  src/dropdown/list/item/_dropdown-list-item.scss
  stories/1-Dropdown.stories.tsx
  stories/utils/constants/_dropdown-story-option-constants.scss
  stories/utils/constants/dropdownStoryOptionConstants.tsx
Labels: Ready for new release

#70 feat(progress-bar): Add ProgressBar Component
  rollup.config.js
  src/index.ts
  src/progress-bar/ProgressBar.tsx
  src/progress-bar/_progress-bar.scss
  stories/9-ProgressBar.stories.tsx
Labels: Ready for new release

#71 feat(number-input): Add NumberInput Component
  src/core/utils/array/arrayUtils.ts
  src/core/utils/dom/domUtils.ts
  src/core/utils/keyboard/keyboardEventConstants.ts
  src/core/utils/number/numberConstants.ts
  src/core/utils/string/stringConstants.ts
  src/dropdown/Dropdown.tsx
  src/dropdown/list/DropdownList.tsx
  src/form/input/Input.tsx
  src/form/textarea/Textarea.tsx
  src/list/item/ListItem.tsx
  src/select/typeahead/TypeaheadSelect.tsx
  stories/0-Form.stories.tsx
Labels: Ready for new release

#72 feat(countdown): Add Countdown component
  rollup.config.js
  src/core/utils/hooks/useCountdownTimer.ts
  src/core/utils/time/timeConstants.ts
  src/core/utils/time/timeTypes.ts
  src/core/utils/time/timeUtils.ts
  src/countdown/Countdown.tsx
  src/countdown/_countdown.scss
  src/countdown/util/countdownTypes.ts
  src/countdown/util/countdownUtils.ts
  src/index.ts
  stories/10-Countdown.stories.tsx
Labels: Ready for new release

#82 fix(file-input): Set file input container as relative positioned
  src/form/input/file/_file-input.scss
Labels: Ready for new release, ready for review

#81 refactor(spinner): Simplify Spinner Component
  src/button/Button.tsx
  src/dropdown/Dropdown.tsx
  src/form/input/file/FileInput.tsx
  src/select/typeahead/TypeaheadSelect.tsx
  src/spinner/Spinner.tsx
  src/spinner/_spinner.scss
  stories/4-Spinner.stories.tsx
Labels: Ready for new release

#80 feat(button): Allow custom Spinner for Button
  src/button/Button.tsx
  src/form/input/file/FileInput.tsx
  stories/1-Dropdown.stories.tsx
  stories/3-Button.stories.tsx
  stories/utils/constants/dropdown/_dropdown-story-option-constants.scss
  stories/utils/constants/dropdown/dropdownStoryOptionConstants.tsx
  stories/utils/constants/spinner/SpinnerStorySample.tsx
  stories/utils/constants/spinner/_spinner-story-sample.scss
Labels: Ready for new release

#78 feat(switch): Add Switch Component
  rollup.config.js
  src/index.ts
  src/switch/Switch.tsx
  src/switch/_switch.scss
  stories/10-Switch.stories.tsx
Labels: Ready for new release, ready for review
