Repository studiobakers/react-ui-toolkit, pull requests merged in 2021-05, with the labels that each got.

#86 build: Add GH workflows for automating npm publish and tagging on github
  .github/workflows/new-version.yml
Labels: Ready for new release

#84 feat(button): Adjust dynamically button width
  package-lock.json
  src/button/Button.tsx
  src/button/_button.scss
  src/dropdown/_dropdown.scss
  src/form/input/file/_file-input.scss
  src/progress-bar/ProgressBar.tsx
  stories/3-Button.stories.tsx
Labels: Ready for new release

#79 feat(toggle): Add Toggle Component
  .eslintrc.js
  rollup.config.js
  src/index.ts
  src/toggle/Toggle.tsx
  src/toggle/_toggle.scss
  src/toggle/item/ToggleItem.tsx
  src/toggle/item/_toggle-item.scss
  src/toggle/util/ToggleContext.tsx
  stories/11-Toggle.stories.tsx
  stories/utils/constants/toggle/toggleStoryOptionConstants.ts
Labels: Ready for new release

#87 fix(root): Fix eslint issues
  .eslintignore
  .eslintrc.js
  src/countdown/util/countdownUtils.ts
  src/form/textarea/Textarea.tsx
  src/progress-bar/ProgressBar.tsx
Labels: Ready for new release, ready for review

#91 fix(core): Add `--isolatedModules` flag
  package.json
  src/core/utils/time/timeTypes.ts
  src/countdown/util/countdownTypes.ts
  src/index.ts
  tsconfig.json
Labels: ready for review

#93 fix(core): Add generic types that exported props
  package.json
  src/index.ts
Labels: ready for review

#66 feat(toast): Add `Toast` component
  .storybook/config.js
  package.json
  rollup.config.js
  src/core/utils/array/arrayUtils.ts
  src/core/utils/function/functionUtils.ts
  src/core/utils/string/stringUtils.ts
  src/index.ts
  src/toast/Toast.tsx
  src/toast/ToastItemContext.tsx
  src/toast/ToastProvider.tsx
  src/toast/close-button/ToastCloseButton.tsx
  src/toast/close-button/_toast-close-button.scss
  src/toast/stack/ToastStack.tsx
  src/toast/stack/_toast-stack.scss
  src/toast/util/toastConstants.ts
  src/toast/util/toastHooks.ts
  src/toast/util/toastReducer.ts
  src/toast/util/toastTypes.ts
  src/toast/util/toastUtils.ts
  src/toggle/util/ToggleContext.tsx
  stories/8-Toast.stories.tsx
  stories/utils/constants/toast/_toast.scss
Labels: Ready for new release, ready for review

#95 feat(typeahead): Add type prop for TypeaheadInput
  src/form/input/Input.tsx
  src/form/input/typeahead/TypeaheadInput.tsx
  src/select/typeahead/TypeaheadSelect.tsx
  stories/5-Typeahead.stories.tsx
Labels: Ready for new release, ready for review

#85 feat(input): Add number input localization utility
  src/core/utils/number/numberConstants.ts
  src/core/utils/number/numberTypes.ts
  src/core/utils/number/numberUtils.ts
  src/form/input/Input.tsx
  stories/0-Form.stories.tsx
  tsconfig.json
Labels: Ready for new release, ready for review

#97 fix(number-input): Decimal part improvements and number-input class
  src/core/utils/number/numberTypes.ts
  src/core/utils/number/numberUtils.ts
  src/form/input/Input.tsx
Labels: Ready for new release, ready for review

#98 fix(toast-provider): Allow control of autoClose via ToastProvider
  .storybook/config.js
  src/toast/Toast.tsx
  src/toast/ToastProvider.tsx
  src/toast/util/toastConstants.ts
  src/toast/util/toastReducer.ts
  src/toast/util/toastTypes.ts
  stories/8-Toast.stories.tsx
Labels: ready for review

#99 fix: Add missing classnames to Toast and Input
  package-lock.json
  package.json
  src/form/input/Input.tsx
  src/toast/Toast.tsx
Labels: ready for review
